### ISSUE TITLE
原書第2刷の変更: p.142, 演習問題19-1, 「一ヵ月が28日よりも少ない」

### ISSUE THREAD

**Issue by hisashim** [ohmsha/the-pragmatic-programmer-ja#10]
p. 142, 演習問題19-1の条件が不正確

変更前

> 一ヶ月（標準的なグレゴリオ暦を使用）が28日よりも少ない。

変更後

> 一ヶ月が28日よりも少ない。

（原書資料によると、標準的なグレゴリオ暦に1752年は含まれない旨、
読者による指摘があったとのこと。）

対象は第1刷。
報告者は編集部。

**Comment by mmurak** [comment]
「standard Gregorian calendar」という言葉の解釈の問題だったわけですね。
1752年9月のカレンダーは2日の翌日が14日になるという変則運用だから
「標準的なグレゴリオ暦」とは言えないというわけですか。

**Comment by hisashim** [comment]
はい、どうもそういうわけらしいです。
第2刷で取り込んだのでcloseします。
