### ISSUE TITLE
p. 110, 「また起こるかどうかどうか知る絶好の機会〜」

### ISSUE THREAD

**Issue by kyanny** [ohmsha/the-pragmatic-programmer-ja#14]
p. 110, 第二段落に「また起こるかどうかどうか知る絶好の機会〜」とありますが、「どうか」が重複していると思います。
（手元のピアソン・エデュケーション刊『達人プログラマー』初版第19刷でも同様に、「また起こるかどうかどうか知る絶好の機会〜」となっていました。残念ながら、ピアソン・エデュケーション版の正誤表が見つからなかったため、この部分に対する訂正があったかどうかは不明です）

修正案:

- 変更前

> また起こるかどうかどうか知る絶好の機会〜

- 変更後

> また起こるかどうか知る絶好の機会〜

問題を見つけた刷数: 第1刷

**Comment by mmurak** [comment]
ご指摘ありがとうございます。
これは私のミスです。　申し訳ありません。　(_ _)
（こんなのが10年も残っていたとは、、、）

**Comment by hisashim** [comment]
@kyanny ありがとうございます。私も見落としていました。恐縮です。
第3刷に向けての課題とさせてください。

**Comment by hisashim** [comment]
第3刷で反映しました。ありがとうございます。
