### ISSUE TITLE
pp. 82, 99, 100, 337, 「ソースコード管理」

### ISSUE THREAD

**Issue by hisashim** [ohmsha/the-pragmatic-programmer-ja#15]
Tip 23をはじめ、ツールを指す場合の 「ソースコード管理」は、
「ソースコード管理システム」とすべきでは。

p. 82

  * 変更前
    > 常に「ソースコード管理」を使用するべきです。

  * 変更後
    > 常に「ソースコード管理」を行うべきです。

p. 99

  * 変更前
    > Tip 23
    > 常にソースコード管理を使用すること

  * 変更後
    > Tip 23
    > 常にソースコード管理システムを使用すること

p. 100

  * 変更前
    > あなた一人ぼっちであってもソース管理を使うようにしてください。
    > ...
    > ソースコード管理が本当に使い物になることを

  * 変更後
    > あなた一人ぼっちであってもソース管理を行うようにしてください。
    > ...
    > ソースコード管理システムが本当に使い物になることを

p. 337

  * 変更前
    > 23. 常にソースコード管理を使用すること .............................. 99
    > ソースコード管理は...

  * 変更後
    > 23. 常にソースコード管理システムを使用すること .............................. 99
    > ソースコード管理システムは...

対象は第1-2刷。
報告者は@kou (Kouhei Sutou) さん。

@hisashim ざっと見た限り該当箇所はpp. 82, 99, 337の3ページだけれど、改めて確認すること。
→p. 100にもあった。

**Comment by mmurak** [comment]
そうですね。「システム」がないとソースコード管理という行為そのものになってしまいます。
よろしくお願いいたします。

**Comment by hisashim** [comment]
節見出しとの兼ね合いもあるので、「ソースコード管理（を使用する）」を一律に
「ソースコード管理システム（を使用する）」とはせず、文脈によっては
「ソースコード管理を行う」などとしようと思います。

**Comment by hisashim** [comment]
第3刷で反映しました。ありがとうございます。
