### ISSUE TITLE
pp. 101, 298, GitHub.comのURLスキームをHTTPSとしては

### ISSUE THREAD

**Issue by hisashim** [ohmsha/the-pragmatic-programmer-ja#16]
GitHub.comのURIスキームがhttpとなっているが、
httpsのほうがより好ましいのではないか
（httpでアクセスするとhttpsへリダイレクトされるとはいえ）。

p. 101, 脚注3

  * 変更前
    > GitHub （http://github.com/ ）があります。

  * 変更後
    > GitHub （https://github.com/ ）があります。

p. 298, URL20

  * ebook PDFのリンク先URLをhttps:// とする。

対象は第1-2刷
報告者は @kou (Sutou Kouhei) さん。

**Comment by mmurak** [comment]
世の中の流れに沿わせるという意味でも、そうした方がよいかと思います。
よろしくお願いいたします。

**Comment by hisashim** [comment]
第3刷で反映されました。ありがとうございます。
