### ISSUE TITLE
p. 193, 「開発してしまう場合 もあります。。」

### ISSUE THREAD

**Issue by hisashim** [ohmsha/the-pragmatic-programmer-ja#17]
p. 193, 第4段落に句点が多いというtypoがある。

  * 変更前
    > 開発してしまう場合もあります。。

  * 変更後
    > 開発してしまう場合もあります。

対象は第1-2刷
報告者は@kou (Kouhei Sutoh) さん。

**Comment by mmurak** [comment]
typeです。　失礼しました。

**Comment by hisashim** [comment]
第3刷で反映されました。ありがとうございます。
