### ISSUE TITLE
p. 199, 演習問題32のコメント「文字列の最後にあるmaxlen 文字を切り落とす」

### ISSUE THREAD

**Issue by hisashim** [ohmsha/the-pragmatic-programmer-ja#18]
p. 199, 演習問題32, string_tail関数のコメントが、実際の挙動と
異なっているのではないか。
文字列末尾を切り落とすのではなく、冒頭を切り落とすのでは。

p. 199

  * 変更前
    > 文字列の最後にあるmaxlen 文字を切り落とす

  * 変更後
    > 末尾からmaxlen文字分が残るよう、文字列を切り詰める

日本語の表現は要検討。

原書

```
This piece of C code might work some of the time,
on some machines. Then again, it might not.
What's wrong?

   /* Truncate string to its last maxlen chars */
   void string_tail(char *string, int maxlen) {
     int len = strlen(string);
     if (len &gt; maxlen) {
       strcpy(string, string + (len - maxlen));
     }
   }

Answer 32: POSIX strcpy isn't guaranteed to work
for overlapping strings. It might happen to work
on some architectures, but only by coincidence.
```

日本語版

```
32. この C プログラムは、あるマシン上では動作する場合があるかもしれま
     せん。しかし、動作しない可能性もあります。何が悪いのでしょうか？
        ->答えは p. 326

  /* 文字列の最後にあるmaxlen文字を切り落とす */
  void string_tail(char *string, int maxlen) {
    int len = strlen(string);
    if (len > maxlen) {
      strcpy(string, string + (len - maxlen));
    }
  }
```

対象は第1-2刷。
報告者は @kou (Kouhei Sutou)さん。

**Comment by mmurak** [comment]
ソースコードを勘違いして読んでました。　これは難しい表現になりますね。
「文字列長がmaxlenを超える場合、全体長がmaxlenとなるよう、左端を切り落とす。」
くらいでしょうか。　名案、募集中。 ^^;

**Comment by yattom** [comment]
「文字列の右側を最大maxlen文字取り出す」
「文字列のmaxlen文字ぶん右側から取り出す」
「文字列の末尾側が残るように、最大maxlen文字に切り詰める」
「文字数がmaxlenに収まるよう、先頭から取り除く」
「文字数がmaxlenを超える部分を先頭側から切り捨てる」
あたりを、思いつきました。

**Comment by mmurak** [comment]
ソースコードで書くと単純なのに、日本語にするとややこしいですね。
私の最初の案（文字列長がmaxlenを超える場合、全体長がmaxlenとなるよう、左端を切り落とす）だと、まるで if (len > maxlen)  string + len - maxlen; return string;になっちゃいますね（元々の関数はvoidだけど）。

「文字列長がmaxlenを超える場合、maxlenに収まるまで左端を捨てる」というのも考えてみましたが、これじゃあcdr呼び出しながら再帰呼び出ししてるみたいだし。

ということで、yattomさんの第3案の「末尾側」を「末尾部分」に変えたバージョンがよさそうですね。　こんな感じで。　↓

「文字列の末尾部分が残るように、最大maxlen文字に切り詰める」

**Comment by hisashim** [comment]
第3刷で反映されました。みなさんありがとうございます。

> /* 文字列の末尾部分が残るように、最大maxlen文字に切り詰める*/
