### ISSUE TITLE
p. 259, 訳注, MakefileとMake

### ISSUE THREAD

**Issue by hisashim** [ohmsha/the-pragmatic-programmer-ja#19]
厳密に言うと、ツールの名前がMake、コマンドの名前がmakeで、
指示を記述するファイルの標準的な名前がMakefileなのでは。

  * 変更前
    > 現在では Makefile の他、maven 、 gradle 、 rake 、 grunt などもよく用いられています。

  * 変更後
    > 現在ではMakeの他、Maven 、Gradle 、Rake 、Grunt などもよく用いられています。

対象は第1-2刷。
報告者は @kou (Kohei Sutou) さん。

**Comment by hisashim** [comment]
本文も同様にツールがMakefileと呼ばれているけれど、とはいえ原文が
こうなっており、意図と意味は分かるので、ママでも許容かしら。

原文:
> We generally compile projects with makefiles, even when using an IDE
> environment. There are several advantages in using makefiles.
> It is a scripted, automatic procedure. We can add in hooks to generate
> code for us, and run regression tests automatically.

日本語訳:
> 我々は通常、 IDE を使用する場合であってもMakefileを用いてプロジェク
> トのコンパイルを行っています*2。Makefileを使用する利点はいくつかありま
> す。これはスクリプト形式になった自動化手続きです。このためMakefileを使
> えば、コードを生成するためのフックの追加や、回帰テストの自動実行が可能に
> なります。

このページはちょっと考えどころです。

**Comment by kou** [comment]
原文には、本文はツールとしてmakefilesと言っているわけではなく、makefileにビルド手順とかを書いてコンパイルしている、と書いているように私には読めました。

なので、訳注の方は、pom.xmlとかRakfeileとかなんとかとかにスクリプトを書くやり方もよく使われています、くらいの方が本文とマッチしそうだなぁと思いました。（pom.xmlにスクリプトを書けるのかわかっていませんが。。。）

**Comment by mmurak** [comment]
Makefileは確かにMakeに指示するためのファイル名ですが、わりと通じてしまうってところがありますよね。
でもrakefileはどうなんだろう？　ちょっと苦しいような気がするので、
「現在ではMakeの他、Maven 、Gradle 、Rake 、Grunt などもよく用いられています」としておき、
「我々は通常、 ・・・」の部分はMakefileのママとした方がよいように感じています。
（IDEを使用する場合であってもMakeを使用してるというのは、確かにIDEがmakeを呼び出しているという点では正しいのでしょうが、ユーザー（開発者）視点から見えるのはMakefileの方でしょうし。）

**Comment by hisashim** [comment]
第3刷で次のように変更しました。ありがとうございます。

本文:
> 我々は通常、IDEを使用する場合であってもMakefileを用いて～

訳注:
> ～現在ではMakeの他、Maven 、Gradle 、Rake 、Grunt などもよく用いられています。
