### ISSUE TITLE
p. 195, 「我々はFredよりも賢く立ち回れるはずです我々は」

### ISSUE THREAD

**Issue by hisashim** [ohmsha/the-pragmatic-programmer-ja#20]
p. 195, 最終行, 句点が欠けている。

  * 変更前
    > 我々はFredよりも賢く立ち回れるはずです我々は偶然になんて頼りません

  * 変更後
    > 我々はFredよりも賢く立ち回れるはずです。我々は偶然になんて頼りません

対象は第1-2刷。
報告者は編集部。

**Comment by mmurak** [comment]
typoです。　(_ _);

**Comment by hisashim** [comment]
第3刷で反映しました。
