### ISSUE TITLE
p. 202, コーヒーを「煎れる」→「淹れる」

### ISSUE THREAD

**Issue by hisashim** [ohmsha/the-pragmatic-programmer-ja#21]
p. 202, コーヒーは「淹れる」か「いれる」としては。

  * 変更前
    > とりあえずコーヒーを煎れてきたほうがよいかもしれません

  * 変更後
    > とりあえずコーヒーを淹れてきたほうがよいかもしれません

対象: 第1-2刷
報告者: 編集部

**Comment by mmurak** [comment]
そうですね。　煎れるだと、豆を煎ってる感じです。
「淹れたて」の方が美味しそうに感じますし。

**Comment by hisashim** [comment]
すみません。これは私の見間違いだったようです。
発行前に、2016-10-06の c91184a で編集されて、第1刷から「淹れて」となっています。
失礼しました。
