### ISSUE TITLE
p. 340, Tip 51, 「政略」

### ISSUE THREAD

**Issue by hisashim** [ohmsha/the-pragmatic-programmer-ja#22]
p. 340, 付録C, Tip 51の「政略」は「政策」としてはどうでしょうか。

要求が、見えにくい政治的な要因から（も）生じているのだ、という意味は
あまり差がないかもしれませんが、本文の対応する部分が「政策」と
なっているので、字面上少し気になりました。wishlist程度です。

```diff
-要求は、仮定、誤解、政略といった層に深く埋められているものである。
+要求は、仮定、誤解、政策といった層に深く埋められているものである。
```

本文, p. 228, 「36 要求の落とし穴」:
> 要求とは通常の場合、さまざまな仮定、誤解、政策の奥底深くに埋められているのです。

付録C, p. 340, 「51. 要求とは拾い集めるものではなく、掘り起こすものである」:
> 要求が見えるところに横たわっていることは希である。要求は、仮定、誤解、政略といった層に深く埋められているものである。

原書, p. 202, 36 The Requirements Pit:
> It doesn't quite work that way. Requirements rarely lie on the
> surface. Normally, they're buried deep beneath layers of assumptions,
> misconceptions, and politics.

報告者: 編集部
対象: 第2刷

**Comment by mmurak** [comment]
そうですね。　政略というと何か「謀をめぐらせている感」がありますし。
政策にしていただければ、、、と考えております。

**Comment by hisashim** [comment]
第3刷で反映しました。ありがとうございます。
