### ISSUE TITLE
Tipのタイトルが本文と付録とで異なるものがある

### ISSUE THREAD

**Issue by hisashim** [ohmsha/the-pragmatic-programmer-ja#24]
Tipのタイトルが、本文と、巻末の「付録C クイックリファレンスガイド」に
掲載されたものとで、文言が異なっている場合がある。

（ @hisashim 異なっていても構わない、あるいは異なっていることに
必然性があるケースはある？ 要確認。
ただの編集ミスなどで表現が分かれてしまったものは、適切なほうに
一致させたいところ。）

* Tip 8
  - p. 17
    > あなたの知識ポートフォリオに対して定期的な投資を行うこと
  - p. 336
    > 常にあなたの知識ポートフォリオに投資すること

* Tip 9
  - p. 19
    > 見聞きしたものごとを批判的な目で分析すること
  - p. 336
    > 見聞きしたことを批判的な目で分析すること

* Tip 10
  - p. 26
    > 伝えることがらと、伝える方法は車の両輪だと考えること
  - p. 336
    > 伝える事柄と、伝える方法は車の両輪だと考えること

* Tip 19
  - p. 79
    > 規律に従ってスケジュールを繰り返し、精度を向上させていくこと
  - p. 337
    > コーディングによってスケジュールを繰り返すこと

* Tip 22（周辺の「エディター」→「エディタ」も同時に修正）
  - p. 93
    > 一つのエディタを熟知すること
  - p. 337
    > 一つのエディターを熟知すること
    > エディターは手の延長となるべきであり、エディターが

* Tip 33
  - p. 139
    > もし起こり得ないというのであれば、表明を用いてそれを保証すること
  - p. 338
    > もし起こり得ないというのであれば、表明を用いてそれを証明すること

* Tip 37
  - p. 165
    > 設定とすべきものを統合しないこと
  - p. 338
    > 設定すべきものを統合しないこと

* Tip 49
  - p. 222
    > ソフトウェアをテストすること、さもなければユーザーにテストを強いることになる
  - p. 339
    > ユーザーがテストする前にソフトウェアをテストすること

* Tip 50
  - p. 224
    > ウィザードの生成コードが理解できないのであれば、ウィザードを使わないこと
  - p. 340
    > 理解できないウィザードのコードを使わないこと

* Tip 55
  - p. 239
    > 枠にとらわれずに考えるのではなく、枠を見つけ出すこと
  - p. 340
    > 枠にとらわれずに考えるのではなく、枠を見つけだすこと

* Tip 69
  - p. 284
    > ユーザーの期待を少しだけ上回ること
  - p. 341
    > ユーザーの期待をやや上回ること

対象: 第1-2刷
報告者: 編集部

**Comment by mmurak** [comment]
基本的には、、、というか本文の方がよいですね。　本文に合わせる方向でお願いいたします。
(_ _)

**Comment by hisashim** [comment]
@mmurak ありがとうございます。たしかに、本文が推敲された結果に、クイックリファレンスを
追従させそこねたように思えます。村上さんにも読者の方にも申し訳ありません。
社内事情が許すか分かりませんが、できる限り本文に合わせる方向で進めたいと思います。

**Comment by hisashim** [comment]
第3刷で反映しました。ありがとうございます。
