### ISSUE TITLE
EPUB版: 2章 8 直交性 リスクの削減

### ISSUE THREAD

**Issue by kyanny** [ohmsha/the-pragmatic-programmer-ja#34]
リスト記法が展開されていないように見える箇所がありました。

<img width="1552" alt="screen_shot_2017-09-26_at_14_24_40" src="https://user-images.githubusercontent.com/10515/30844035-d6234b12-a2c7-11e7-88ed-6dd0d865b15c.png">

対象: EPUB版 バージョン 3.0

**Comment by hisashim** [comment]
@kyanny ご指摘ありがとうございます。
現時点の最新刷である第4刷相当のEPUBで、問題を確認しました。

段落の区切りがおかしくなっていますが、正しくはこうでしょうね。

> 直交的なアプローチは、どのような開発においても...
> 
>   * コード中の問題発生部分を隔離できるようになります。...さらにその部分を...
>   * 結果的にシステムはより堅牢になります。...
>   * 直交しているシステムは、...
>   * 特定のサードパーティコンポーネントへの...
> 
> では、あなたの仕事に直交原則を適用するための方法を...

失礼しました。修正候補にします。

**Comment by hisashim** [comment]
ご報告が遅くなりましたが、おかげさまで、2017-09ごろにp4.1（電子版のみの先行更新）で
反映されました。
近日発行予定のp5.0（第5刷）以降では、紙版とEPUB版の見た目とバージョンが
一致するようになるかと思います。
丁寧なご指摘をありがとうございます。
