### ISSUE TITLE
p. 98, 「キー最も大事なユーザーインタフェースの一つとして、〜」

### ISSUE THREAD

**Issue by kyanny** [ohmsha/the-pragmatic-programmer-ja#5]
p. 98, 第一段落の冒頭が「キー最も大事なユーザーインタフェースの一つとして、〜」となっているが、「キー」が不要と思われます。
（手元のピアソン・エデュケーション刊『達人プログラマー』初版第19刷では、「もっとも大事なユーザー・インタフェースの一つとして、〜」となっていました）

修正案:

- 変更前

> キー最も大事なユーザーインタフェースの一つとして、〜

- 変更後

> 最も大事なユーザーインタフェースの一つとして、〜

問題を見つけた刷数: 第1刷

**Comment by hisashim** [comment]
ご指摘ありがとうございます。
確認したところ、編集部のタイプミスだと思います。

**Comment by hisashim** [comment]
@kyanny やはり編集部のtypoでした。恐縮です。
ちょうど増刷に向けて作業をしておりまして、第2刷に修正が反映されるよう手配しました。
編集が至らなかったところを見つけて教えてくださって、ありがとうございます。

**Comment by kyanny** [comment]
@hisashim 
ご対応ありがとうございます！このイシューは閉じてしまったほうが良いでしょうか？

**Comment by hisashim** [comment]
反応が遅くてすみません。
おかげさまで第2刷に反映しましたので、closeします。
