### ISSUE TITLE
原書第2刷の変更: p. 129, sqrt関数

### ISSUE THREAD

**Issue by hisashim** [ohmsha/the-pragmatic-programmer-ja#9]
p. 129, Eiffelの```sqrt```で```Currernt.abs```が考慮されていない。

変更前

>```     ((Result * Result) - Current).abs < epsilon;```

変更後

>```     ((Result*Result) - Current).abs <= epsilon*Current.abs;```

対象は第1刷。
報告者は編集部。

**Comment by mmurak** [comment]
あれ？　なぜCurrent.absを乗じてるんでしょうね？
、、、と一瞬思いましたが、そっか。　epsilon誤差が拡大するって話ですね。

**Comment by hisashim** [comment]
ご確認ありがとうございます。
こちらでの報告が遅くなりましたが、問題なさそうなので、第2刷で取り込みました。
